// This file is generated by bench2vlog.py by littleshamoo
//   options: -l tsmc 
module c17 ( G1gat, G2gat, G3gat, G6gat, G7gat, G22gat, G23gat);

input G1gat;
input G2gat;
input G3gat;
input G6gat;
input G7gat;

output G22gat;
output G23gat;

NAND2XL U_G10gat (.A(G1gat), .B(G3gat), .Y(G10gat) );
NAND2XL U_G11gat (.A(G3gat), .B(G6gat), .Y(G11gat) );
NAND2XL U_G16gat (.A(G2gat), .B(G11gat), .Y(G16gat) );
NAND2XL U_G19gat (.A(G11gat), .B(G7gat), .Y(G19gat) );
NAND2XL U_G22gat (.A(G10gat), .B(G16gat), .Y(G22gat) );
NAND2XL U_G23gat (.A(G16gat), .B(G19gat), .Y(G23gat) );

endmodule
